### ISSUE TITLE
WYSIWYG editor vs. markdown textarea

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/editor#125]
This is not really an editor *issue*, more a result of having such a field.

Let's say you're using the editor for a client project. It will probably go something like this: client sees editor, client loves the editor. I'm pretty sure about that.

But at some point you will probably still need some kind of `textarea` fields with simple formatting like bold, italic and links. Now there are two approaches:
1. Using an editor field with `allowed` set to `text` only. It's a bit too bulky for that purpose, though.
2. Using a textarea field, introducing the client to a whole new formatting concept.

I don't have a concrete solution for this problem, but I think it's a topic worth discussing.

**Comment by lukasbestle** [comment]
That's a good point! I think that a second, reduced UI with a limited set of features would be really nice.

**Comment by texnixe** [comment]
I agree, a stripped-down editor would be great for this purpose.

**Comment by medienbaecker** [comment]
There are some fields with a `multiple: false` option, maybe a similar option would be a good idea for the editor?

**Comment by lukasbestle** [comment]
What about a `ui` option:

```
ui: full (default)
ui: reduced
... (other options possible in the future)
```

**Comment by bastianallgeier** [comment]
The editor is built on my own ProseMirror wrapper component that could easily be turned into its own field. That field would then just be able to handle single paragraphs with simple inline styles (bold, italic, links, etc) This could even ship with the editor. I'm just worried that there will be new requests for that particular field to add lists, paragraphs, headlines, etc., which is not possible / wanted.

**Comment by medienbaecker** [comment]
I think such a field would be enough for a lot of use cases. But of course at some point you need multiple paragraphs, headlines, etc. — this would just make things more complicated.

Is it possible to add the ProseMirror functionality to the `textarea`? With some kind of markdown export/import? Maybe as an option?

**Comment by bastianallgeier** [comment]
As soon as paragraphs, headlines, etc. need to be added, we are back in full-blown WYSIWG land and that's something I want to avoid at all costs. Then it's still better to build your own WYSIWYG field with the library of choice.

**Comment by texnixe** [comment]
Once you need headlines or lists etc. you might as well use the full-blown editor and disable what you do not need. Something in-between doesn't really make sense, IMO, both from a user point of view and from the developer having to maintain this.

**Comment by medienbaecker** [comment]
I totally agree.
Maybe it would make sense to further think about the different use cases? Off the top of my head I can't think of something that wouldn't either be a single paragraph or a full-blown editor.

**Comment by bastianallgeier** [comment]
I was thinking about adding an inline option to the editor field. Then you could easily switch between both use cases.

**Comment by medienbaecker** [comment]
How will such an inline editor look like? Or in other words: how would you differentiate it from a textarea and the full editor?

The inline editor should probably not be as big as the full blown variant. But stripping it down will eventually lead to a rectangle with text inside. Just like the textarea.

**Comment by bastianallgeier** [comment]
There are not too many options here. Would it be that bad to make it look like a regular text / textarea field?

**Comment by bastianallgeier** [comment]
I would probably just leave away the button bar and keep the floating toolbar.

**Comment by medienbaecker** [comment]
I'm just worried about the user trying to insert Kirbytags, expecting paragraphs instead of line breaks, etc. when the field looks exactly like a textarea with `buttons: false`.

**Comment by texnixe** [comment]
@medienbaecker But from what you first outlined above, would these users even get to know a regular textarea field? I thought the original idea was to not have different ways to enter content?

**Comment by medienbaecker** [comment]
@texnixe You're right. It should probably just be avoided to use both in one project.

**Comment by nilshoerrmann** [comment]
Having an inline mode for Editor would really be great as it'll help keeping the input methods consistent. I'd really like this to be just an additional option for Editor and not an additional field. Two reasons:

1. If I'm in need of an inline version of Editor, I'll most likely already use Editor in other places.
2. We usually start using Kirby early in the design and development process. This results in blueprint changes throughout development. Having block and inline Editor in one field would ease this "dynamic development".

I like the idea posted by @medienbaecker to reuse known Kirby field options. What do you think about the following additional settings:

- `multiple: false` – this would make the Editor single block only. It's useful for inline content but might also be useful for content that should be limited to a single block.
- `default: inline|paragraph` – this would allow for the setting of the initial block type used when the Editor is first loaded. `default: inline` used in combination with `multiple: false` would give us the inline editor this issue is all about. But this setting would also allow us to make the Editor start with a list for example if that's what's needed in the context of the page. `inline` would be it's own block, returning all its content without a wrapping element.
- `min: number` / `max: number` – having these bounds would allow for an even more finegrained setup. `multiple: false` and `max: 1` would actually be aliases for the same thing.

This would introduce an inline mode while offering extended setup options beyond that single use case.

**Comment by bastianallgeier** [comment]
✅ I decided to go for a new inline option: 

```
fields: 
  text: 
    type: editor
    inline: true
```

There are no more blocks in this mode so I don't think multiple or min, max options make sense. It's a completely different kind of editor mode.
