### ISSUE TITLE
Handling empty content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#130]
Editor offers handy methods to fetch content parts, like `$page->text()->block()->first()->html()`. This works perfectly if content exists but it fails with no content available:

> Call to a member function html() on null

While technically that message is correct, I'd expect the field to fail silently here and just return an empty string. Otherwise, using the field inside templates will require a lot of conditions to make sure the frontend won't break under all circumstances.

**Comment by bastianallgeier** [comment]
I'm afraid I have to close this. We would need to refactor the entire Collection class in order to get this working and then the behaviour for blocks would no longer be consistent with all other collections in Kirby. 

You can do `$page->text()->block()->first()` btw. This will also give you the HTML for the block and it fails silently.
