### ISSUE TITLE
Bug: plugin folder name may break editor

### ISSUE THREAD

**Issue by mauricerenck** [getkirby/editor#132]
When creating your own block plugin, the name of the plugin folder can break the editor.

Example: 

1. Create a simple block plugin extending the paragraph, name it `columns-block` use the editor in a blueprint, it will throw an error in the console `ReferenceError: editor is not defined`. Then editor won't work

2. Rename the plugin folder to `zzz-columns-block` the plugin will now work, no error is thrown.

It seems like the plugin name must start with a letter in the alphabet after the letter `e` to make sure the editor-plugin is loaded before the block-plugin is.

**Comment by gnitter** [comment]
I can reproduce the issue with my block plugin

**Comment by bastianallgeier** [comment]
✅

**Comment by janherman** [comment]
Has this problem been resolved? After I tried to create my block plugin I got the exact same error. Renaming the plugin and the folder fixed the issue.

**Comment by gnitter** [comment]
Since there must be some kind of load order, i think, Kirby seems to load the plugins in an alphabetical order. This could be solved with some kind of plugin-dependecy-handling inside the plugins, which defines on what other plugins a plugin depends. But that's something for the 'Suggestions' category in the Kirby forum... :-)
