### ISSUE TITLE
Editor deletes wrong block

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#146]
I'm trying to delete the last line block:

![Bildschirmfoto am 2019-11-01 um 13 41 45](https://user-images.githubusercontent.com/25466/68025552-637a1e00-fcad-11e9-8248-95e5c979d325.png)

Instead, the field deletes the first block:

![Bildschirmfoto am 2019-11-01 um 13 41 52](https://user-images.githubusercontent.com/25466/68025561-6d038600-fcad-11e9-86e1-95017b9ccf8a.png)

**Comment by nilshoerrmann** [comment]
Hm 🤔, seems like there is something wrong in general with block selection in the latest Editor version: if I try to insert a new block – independent of the starting block – the new one is always created as last block.

**Comment by bastianallgeier** [comment]
I cannot reproduce this at all. Is this via keyboard input or by clicking the delete button in the dropdown menu?

**Comment by nilshoerrmann** [comment]
It happens when using the context menu with the mouse.

**Comment by nilshoerrmann** [comment]
By the way, this is a multilingual install with German and English translations.

**Comment by bastianallgeier** [comment]
✅

**Comment by skyeewers** [comment]
I've been running into an issue very similar to this where the Kirby Editor would delete blocks seemingly in random order and insert new ones the same way. Turns out the issue originated from my own custom block types that were missing a proper implementation of the `focus()` method, resulting in the editor not being able to properly "find" the block's indexes.  

I sadly can't open a PR for the wiki of this repo but I'd suggest maybe adding a mention of the importance of this method to the ["Block extensions"](https://github.com/getkirby/editor/wiki/Block-extensions) page of the documentation to prevent other people from running into this kind of issue in the future.
