### ISSUE TITLE
Pressing Delete button at the end of the block deletes the whole block

### ISSUE THREAD

**Issue by janherman** [getkirby/editor#218]
**Describe the bug**
Pressing "Delete" button at the end of the block deletes the whole block. It happens with headings, paragraphs and list items.

**To Reproduce**
1. Create a new paragraph in editor. Put some content into it.
2. Place the cursor at the end of the paragraph.
3. Press "Delete" button.
4. The whole block is deleted.

**Expected bahavior:**
I think this should not happen, when there is some content in the block. 

**Kirby Version**
Kirby 3.3.4
Kirby Editor 1.0.2

**Comment by bastianallgeier** [comment]
Which browser and OS do you use?

**Comment by janherman** [comment]
My OS is Windows 10. I tried different browsers (latest versions of Chrome, Firefox and Edge), it happens in every one of them.

**Comment by WebMechanic** [comment]
Same here, Firefox/74, Win10 Pro; 
cms 3.3.4, editor 1.0.2

Hit "delete" in order to _join two subsequent list items_ but instead the 1st got deleted. 
Unfortunately classic "undo" (Ctrl-Z) doesn't work either which leaves me only with "Revert" to essentially destroy all edits made.

I need to revert my blueprints to use textarea again: the lack of undo and a killer-delete are absolute show stoppers.

**Comment by bastianallgeier** [comment]
@WebMechanic @janherman I totally agree that this is a big issue. It seems to be a Windows vs. Mac keyboard shortcut problem at first sight. This doesn't happen on a Mac. I will try to fix this asap.

**Comment by WebMechanic** [comment]
I switched to `k-community/markdown-field` for the time being which doesn't have this issue and also handles Undo properly

**Comment by seehat** [comment]
Same here on a Mac: 
- Editor 1.0.2
- Kirby 3.3.6
- Chrome 81.0.4044.129

**Comment by bastianallgeier** [comment]
I finally found a fix! ✅
