### ISSUE TITLE
Empty blocks

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#35]
The editor currently stores empty blocks. I'm not sure if that is always desirable. While I understand to tension to not mess with the author's intensions, it doesn't make sense to keep empty paragraphs from a semantical point in my eyes. At least, not for closing empty paragraphs (even more if there was a placeholder for adding new blocks, see #30).

**Comment by bastianallgeier** [comment]
That's something you can easily control in a custom snippet. That's why I'd close this.

**Comment by nilshoerrmann** [comment]
So you think it's correct to keep empty blocks in the UI after saving? I'd expect the field to clean this up actually.

**Comment by yandodov** [comment]
Empty paragraphs are omitted in Markdown, for example, because there's no concrete rules for where paragraphs start and end. If I have 9 blank lines, do I have 9 paragraphs with 1 empty line, or 3 paragraphs with 3 empty lines?

In the editor, however, paragraphs are cleanly separated, which means that if the author left an empty one - it's his decision. It probably isn't a good decision from a markup standpoint, but that doesn't change the fact he wants it.
